#!/usr/bin/env bash

echo "Linking dotfiles."
for folder in gem git tmux vim zsh; do
  stow --target=$HOME --ignore=example $folder
done

if [[ -d "$HOME/.vim/autoload/plug.vim" ]]; then
  echo "Updating vim packages..."
else
  echo "Installing plug.vim"
  if [ ! -d "$HOME/.vim/autoload" ]; then
    mkdir -p $HOME/.vim/autoload
  fi
  curl -fLo $HOME/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
vim -c "PlugInstall" -c "qa!"

