# taps
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

# brews
brew "fasd"                       # allow quick switching directories
brew "macvim"                     # mac specific vim
brew "reattach-to-user-namespace" # enable clipboard with tmux
brew "tmux"                       # allow easier split panes
brew "tree"                       # show directory structure in an easy to read format
brew "stow"                       # create links to dotfiles
