#!/usr/bin/env bash

brew_path=$(which brew)
if [ -x "$brew_path" ] ; then
  echo "Install Homebrew Packages"
  echo
else
  echo "Installing homebrew"
  echo
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  if [ $? -ne 0 ]; then
    echo "Error installing homebrew. Bailing..."
    echo
    exit 1;
  else
    brew doctor
    if [ $? -ne 0 ]; then
      echo "Brew Doctor is not happy. Bailing..."
      echo
      exit 1;
    fi
  fi
fi

# Update brew if needed
brew update
brew upgrade

# Install brews
brew install fasd # allow jumping to recent folders with `z foo`
brew install macvim --with-override-system-vim # replace the system vim with macvim
brew install reattach-to-user-namespace # enable tmux pasteboard
brew install stow # easier symlinking of dotfiles
brew install tmux # make split terminals easier to handle
brew install tree # quickly see a folder structure

# Cleanup old brews
brew cleanup
